### ISSUE TITLE
MacOS ARM64 build failing

### ISSUE THREAD

**Issue by buggymcbugfix** [coq/platform#286]
Trying to install from source on my M1 mac, I hit the following errors:
```#=== ERROR while compiling z3.4.8.14 ==========================================#
# context              2.1.3 | macos/arm64 | ocaml-option-flambda.1 ocaml-variants.4.13.1+options | https://opam.ocaml.org#b46e7546
# path                 ~/.opam/__coq-platform.2022.04.1~8.15~2022.04/.opam-switch/build/z3.4.8.14
# command              ~/.opam/opam-init/hooks/sandbox.sh build python3 scripts/mk_make.py --ml
# exit-code            1
# env-file             ~/.opam/log/z3-79405-ecd13a.env
# output-file          ~/.opam/log/z3-79405-ecd13a.out
### output ###
# [...]
# Copied '__init__.cpython-310.pyc'
# Copied 'z3printer.cpython-310.pyc'
# Testing ocamlc...
# Testing ocamlopt...
# Traceback (most recent call last):
#   File "/Users/vl200/.opam/__coq-platform.2022.04.1~8.15~2022.04/.opam-switch/build/z3.4.8.14/scripts/mk_make.py", line 18, in <module>
#     mk_bindings(API_files)
#   File "/Users/vl200/.opam/__coq-platform.2022.04.1~8.15~2022.04/.opam-switch/build/z3.4.8.14/scripts/mk_util.py", line 3044, in mk_bindings
#     check_ml()
#   File "/Users/vl200/.opam/__coq-platform.2022.04.1~8.15~2022.04/.opam-switch/build/z3.4.8.14/scripts/mk_util.py", line 450, in check_ml
#     raise MKException('Failed testing ocamlopt compiler. Set environment variable OCAMLOPT with the path to the Ocaml native compiler. Note that ocamlopt may require flexlink to be in your path.')
# mk_exception.MKException: 'Failed testing ocamlopt compiler. Set environment variable OCAMLOPT with the path to the Ocaml native compiler. Note that ocamlopt may require flexlink to be in your path.'


#=== ERROR while compiling lablgtk3.3.1.2 =====================================#
# context              2.1.3 | macos/arm64 | ocaml-option-flambda.1 ocaml-variants.4.13.1+options | https://opam.ocaml.org#b46e7546
# path                 ~/.opam/__coq-platform.2022.04.1~8.15~2022.04/.opam-switch/build/lablgtk3.3.1.2
# command              ~/.opam/opam-init/hooks/sandbox.sh build dune build -p lablgtk3 -j 6
# exit-code            1
# env-file             ~/.opam/log/lablgtk3-79405-d4c35d.env
# output-file          ~/.opam/log/lablgtk3-79405-d4c35d.out
### output ###
# Undefined symbols for architecture arm64:
# [...]
#      (maybe you meant: _ml_gdk_pixbuf_scale_bc, _ml_gdk_pixbuf_scale )
#   "_gdk_pixdata_deserialize", referenced from:
#       _ml_GdkPixbuf_deserialize in liblablgtk3_stubs.a(ml_gdkpixbuf.o)
#   "_gdk_pixdata_from_pixbuf", referenced from:
#       _ml_GdkPixbuf_serialize in liblablgtk3_stubs.a(ml_gdkpixbuf.o)
#   "_gdk_pixdata_serialize", referenced from:
#       _ml_GdkPixbuf_serialize in liblablgtk3_stubs.a(ml_gdkpixbuf.o)
# ld: symbol(s) not found for architecture arm64
# clang: error: linker command failed with exit code 1 (use -v to see invocation)
# File "caml_startup", line 1:
# Error: Error during linking (exit code 1)


#=== ERROR while compiling gmp-ecm.7.0.3 ======================================#
# context              2.1.3 | macos/arm64 | ocaml-option-flambda.1 ocaml-variants.4.13.1+options | https://opam.ocaml.org#b46e7546
# path                 ~/.opam/__coq-platform.2022.04.1~8.15~2022.04/.opam-switch/build/gmp-ecm.7.0.3
# command              ~/.opam/opam-init/hooks/sandbox.sh build ./configure --prefix /Users/vl200/.opam/__coq-platform.2022.04.1~8.15~2022.04 CPPFLAGS=-I/opt/homebrew/include LDFLAGS=-L/opt/homebrew/lib
# exit-code            1
# env-file             ~/.opam/log/gmp-ecm-79405-373091.env
# output-file          ~/.opam/log/gmp-ecm-79405-373091.out
### output ###
# [...]
# checking for setvbuf... yes
# checking for fallocate... no
# checking for aio_read... yes
# checking for aio_init... no
# checking for _fseeki64... no
# checking for _ftelli64... no
# checking for malloc_usable_size... no
# checking for gmp.h... yes
# checking for recent GMP... yes
# checking if GMP is MPIR... no
# checking whether we can link against GMP... no
# configure: error: Could not link against GMP library.


#=== ERROR while compiling gappa.1.4.0 ========================================#
# context              2.1.3 | macos/arm64 | ocaml-option-flambda.1 ocaml-variants.4.13.1+options | https://opam.ocaml.org#b46e7546
# path                 ~/.opam/__coq-platform.2022.04.1~8.15~2022.04/.opam-switch/build/gappa.1.4.0
# command              ~/.opam/opam-init/hooks/sandbox.sh build ./configure CXXFLAGS=-I/opt/homebrew/include LDFLAGS=-L/opt/homebrew/lib --prefix=/Users/vl200/.opam/__coq-platform.2022.04.1~8.15~2022.04
# exit-code            1
# env-file             ~/.opam/log/gappa-79405-7fc1b0.env
# output-file          ~/.opam/log/gappa-79405-7fc1b0.out
### output ###
# [...]
# checking whether gcc accepts -g... yes
# checking for gcc option to enable C11 features... (cached) none needed
# checking how to run the C preprocessor... gcc -E
# checking how to run the C++ preprocessor... g++ -E
# checking for g++... g++
# checking whether the compiler supports GNU C++... (cached) yes
# checking whether g++ accepts -g... yes
# checking for g++ option to enable C++11 features... (cached) none needed
# checking how to run the C++ preprocessor... g++ -E
# checking whether g++ supports C++11 features with -std=gnu++11... yes
# checking for __gmpz_init in -lgmp... no
# configure: error:  *** Unable to find GMP library (http://www.swox.com/gmp/)


#=== ERROR while compiling coq.8.15.2 =========================================#
# context              2.1.3 | macos/arm64 | ocaml-option-flambda.1 ocaml-variants.4.13.1+options | file:///Volumes/case-sensitive/coq/platform-2022.04.1/opam/opam-repository
# path                 ~/.opam/__coq-platform.2022.04.1~8.15~2022.04/.opam-switch/build/coq.8.15.2
# command              ~/.opam/opam-init/hooks/sandbox.sh build make COQ_USE_DUNE= -j6
# exit-code            2
# env-file             ~/.opam/log/coq-79405-3210bf.env
# output-file          ~/.opam/log/coq-79405-3210bf.out
### output ###
# Undefined symbols for architecture arm64:
# [...]
#   "___gmpz_root", referenced from:
#       _ml_z_root in libzarith.a(caml_z.o)
#   "___gmpz_rootrem", referenced from:
#       _ml_z_rootrem in libzarith.a(caml_z.o)
# ld: symbol(s) not found for architecture arm64
# clang: error: linker command failed with exit code 1 (use -v to see invocation)
# File "caml_startup", line 1:
# Error: Error during linking (exit code 1)
# make[1]: *** [_build/install/default/bin/coqc] Error 1
# make[1]: *** Waiting for unfinished jobs....
# make: *** [submake] Error 2

```
I have tried rerunning the build script, to no avail.

**Comment by buggymcbugfix** [comment]
Not sure if relevant, but:
`[WARNING] Opam package conf-python-3.9.0.0 depends on the following system package that can no longer be found: python@3`
On my system the executable is called `python3`

**Comment by MSoegtropIMC** [comment]
I guess you migrated your data from an Intel Mac to a M1 Mac including a Homebrew or Macports installation with a lot of x86 libraries. Basically this does work because the M1 can emulate x86 code, but you have to decide if you want to compile for M1 or for x86 and stick to this decision. You can't mix and match x86 and ARM code in Homebrew or Macports - it is one or the other.

The Coq Platform scripts assume your Homebrew / MacPorts installation contains arm and not x86 libraries. It doesn't make a lot of sense to compile Coq for x86 on a M1 machine.

So please remove and reinstall Homebrew and or MacPorts so that they produce ARM libraries. You might also need to reinstall Xcode - I have no experience with this.

Please report here if this works and close.

**Comment by MSoegtropIMC** [comment]
For your info: the Mac Installer contains x86 binaries - this also works, but is a bit slow. It is fine for student homework but not for serious work.

IRNIA is working on infrastructure to create ARM binary installers.

**Comment by buggymcbugfix** [comment]
D'oh yes, this was it. I completely uninstalled `brew` and all the packages installed with it and reinstalled everything and now it installed fine.

Is there a way to reliably detect from the installation script if someone has x86 dependencies? If not, we could at least put a note into the README.

**Comment by MSoegtropIMC** [comment]
I should have told you upfront to come up with a script to detect the situation - it has hard to test such a script without being in it ...

But I guess a note in the readme in a prominent place on the situation would already improve things.

**Comment by buggymcbugfix** [comment]
Oops no, I misread the output, sorry. Scrolling further up, I got some errors (see below).

Maybe this is due to some previous build artifacts sticking around? (I have the line `===== opam switch already exists =====`.)

```
#=== ERROR while compiling lablgtk3.3.1.2 =====================================#
# context              2.1.3 | macos/arm64 | ocaml-option-flambda.1 ocaml-variants.4.13.1+options | https://opam.ocaml.org#b52ec315
# path                 ~/.opam/__coq-platform.2022.04.1~8.15~2022.04/.opam-switch/build/lablgtk3.3.1.2
# command              ~/.opam/opam-init/hooks/sandbox.sh build dune build -p lablgtk3 -j 4
# exit-code            1
# env-file             ~/.opam/log/lablgtk3-48999-16728a.env
# output-file          ~/.opam/log/lablgtk3-48999-16728a.out
### output ###
# [...]
# File "src/tools/dune", line 16, characters 7-18:
# 16 |  (name lablgladecc)
#             ^^^^^^^^^^^
# (cd _build/default && /Users/vl200/.opam/__coq-platform.2022.04.1~8.15~2022.04/bin/ocamlopt.opt -w -40 -w -3-6-27 -g -o src/tools/lablgladecc.exe /Users/vl200/.opam/__coq-platform.2022.04.1~8.15~2022.04/lib/ocaml/unix.cmxa -I /Users/vl200/.opam/__coq-platform.2022.04.1~8.15~2022.04/lib/ocaml /Users/vl200/.opam/__coq-platform.2022.04.1~8.15~2022.04/lib/ocaml/threads/threads.cmxa -I /Users/vl20[...]
# ld: warning: directory not found for option '-L/usr/local/opt/freetype/lib'
# ld: warning: directory not found for option '-L/usr/local/Cellar/fontconfig/2.14.0/lib'
# ld: warning: directory not found for option '-L/usr/local/opt/freetype/lib'
# ld: warning: directory not found for option '-L/usr/local/Cellar/cairo/1.16.0_5/lib'
# ld: library not found for -lfreetype
# clang: error: linker command failed with exit code 1 (use -v to see invocation)
# File "caml_startup", line 1:
# Error: Error during linking (exit code 1)


#=== ERROR while compiling gappa.1.4.0 ========================================#
# context              2.1.3 | macos/arm64 | ocaml-option-flambda.1 ocaml-variants.4.13.1+options | https://opam.ocaml.org#b52ec315
# path                 ~/.opam/__coq-platform.2022.04.1~8.15~2022.04/.opam-switch/build/gappa.1.4.0
# command              ~/.opam/opam-init/hooks/sandbox.sh build ./remake --jobs=4
# exit-code            1
# env-file             ~/.opam/log/gappa-48999-2281e5.env
# output-file          ~/.opam/log/gappa-48999-2281e5.out
### output ###
# [...]
# Failed to build src/parser/ring.o
# Failed to build src/proofs/basic_proof.o
# Failed to build src/proofs/dichotomy.o
# Failed to build src/proofs/proof_graph.o
# Failed to build src/proofs/property.o
# Failed to build src/proofs/rewriting.o
# Failed to build src/proofs/schemes.o
# Failed to build src/proofs/updater.o
# Failed to build src/main.o
# Failed to build src/parameters.o
# Failed to build src/gappa
# Failed to build all



<><> Error report <><><><><><><><><><><><><><><><><><><><><><><><><><><><><>  🐫 
┌─ The following actions failed
│ λ build gappa    1.4.0
│ λ build lablgtk3 3.1.2
└─ 
┌─ The following changes have been performed (the rest was aborted)
│ ↻ recompile conf-python-3                9.0.0
│ ∗ install   coq                          8.15.2
│ ∗ install   coq-aac-tactics              8.15.1
│ ∗ install   coq-bignums                  8.15.0
│ ∗ install   coq-compcert                 3.10
│ ∗ install   coq-coqeal                   1.1.0
│ ∗ install   coq-coqprime                 1.1.1
│ ∗ install   coq-coqprime-generator       1.1.1
│ ∗ install   coq-coquelicot               3.2.0
│ ∗ install   coq-corn                     8.13.0
│ ∗ install   coq-deriving                 0.1.0
│ ∗ install   coq-dpdgraph                 1.0+8.15
│ ∗ install   coq-elpi                     1.13.0
│ ∗ install   coq-equations                1.3+8.15
│ ∗ install   coq-ext-lib                  0.11.6
│ ∗ install   coq-extructures              0.3.1
│ ∗ install   coq-flocq                    4.0.0
│ ∗ install   coq-flocq3                   3.4.3
│ ∗ install   coq-gappa                    1.5.1
│ ∗ install   coq-gappa-flocq3             1.5.1
│ ∗ install   coq-hammer                   1.3.2+8.15
│ ∗ install   coq-hammer-tactics           1.3.2+8.15
│ ∗ install   coq-hierarchy-builder        1.2.1
│ ∗ install   coq-hott                     8.15
│ ∗ install   coq-interval                 4.4.0
│ ∗ install   coq-interval-flocq3          4.4.0
│ ∗ install   coq-iris                     3.6.0
│ ∗ install   coq-iris-heap-lang           3.6.0
│ ∗ install   coq-libhyps                  2.0.5
│ ∗ install   coq-math-classes             8.15.0
│ ∗ install   coq-mathcomp-algebra         1.14.0
│ ∗ install   coq-mathcomp-algebra-tactics 0.3.0
│ ∗ install   coq-mathcomp-analysis        0.5.0
│ ∗ install   coq-mathcomp-bigenough       1.0.1
│ ∗ install   coq-mathcomp-character       1.14.0
│ ∗ install   coq-mathcomp-field           1.14.0
│ ∗ install   coq-mathcomp-fingroup        1.14.0
│ ∗ install   coq-mathcomp-finmap          1.5.1
│ ∗ install   coq-mathcomp-multinomials    1.5.5
│ ∗ install   coq-mathcomp-real-closed     1.1.2
│ ∗ install   coq-mathcomp-solvable        1.14.0
│ ∗ install   coq-mathcomp-ssreflect       1.14.0
│ ∗ install   coq-mathcomp-zify            1.2.0+1.12+8.13
│ ∗ install   coq-menhirlib                20220210
│ ∗ install   coq-mtac2                    1.4+8.15
│ ∗ install   coq-ott                      0.32
│ ∗ install   coq-paramcoq                 1.1.3+coq8.15
│ ∗ install   coq-quickchick               1.6.1
│ ∗ install   coq-record-update            0.3.0
│ ∗ install   coq-reduction-effects        0.1.3
│ ∗ install   coq-reglang                  1.1.3
│ ∗ install   coq-relation-algebra         1.7.7
│ ∗ install   coq-serapi                   8.15.0+0.15.0
│ ∗ install   coq-simple-io                1.7.0
│ ∗ install   coq-stdpp                    1.7.0
│ ∗ install   coq-unicoq                   1.6+8.15
│ ∗ install   coq-unimath                  20220204
│ ∗ install   coq-vst                      2.9.1
│ ∗ install   gmp-ecm                      7.0.3
│ ∗ install   z3                           4.8.14
│ ∗ install   z3_tptp                      4.8.14
└─ 

<><> z3.4.8.14 installed successfully <><><><><><><><><><><><><><><><><><><>  🐫 
=> Z3 4.8.13 changed the linking mode from static to dynamic.
   This change is silent and potentially breaking.
   Please make sure that you don't require static binaries in the programs
   using Z3.

The former state can be restored with:
    /opt/homebrew/bin/opam switch import
"/Users/vl200/.opam/__coq-platform.2022.04.1~8.15~2022.04/.opam-switch/backup/state-20220920105018.export"
```

**Comment by MSoegtropIMC** [comment]
I have (Intel Mac):
```
~$ opam var arch
x86_64
```
I guess you have something different. 

The question is how one could ask MacPorts and Homebrew about their view on things.

**Comment by MSoegtropIMC** [comment]
And yes, I guess you need to recreate the switch (press "d" for delete when you are asked).

**Comment by buggymcbugfix** [comment]
On brew there is no (easy) way of querying the arch.

**Comment by buggymcbugfix** [comment]
Right, so deleting the switch did the trick.

The arch for executables and dylibs can be checked with the `file` command:

``` shell
# prebuilt binary release
$ file $(which coqc)
/Applications/Coq-Platform~8.15~2022.04.app/Contents/Resources/bin/coqc: Mach-O 64-bit executable x86_64

# build from source
$ file $(which coqc)                        
/Users/vl200/.opam/__coq-platform.2022.04.1~8.15~2022.04/bin/coqc: Mach-O 64-bit executable arm64

$ file /opt/homebrew/Cellar/gmp/6.2.1_1/lib/libgmp.dylib 
/opt/homebrew/Cellar/gmp/6.2.1_1/lib/libgmp.dylib: Mach-O 64-bit dynamically linked shared library arm64
```

Not sure if this is helpful at all.

**Comment by MSoegtropIMC** [comment]
Yes, it might be a method to install some dependency with opam depext, query the path of the dependency and then use file to check what architecture we are on.
